package cn.com.mcopy.init;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.PropertySource;
import org.springframework.core.env.Environment;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.annotation.Resource;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by ucenter on 2016/10/15.
 */
@PropertySource({"classpath:config/db.properties"})
public class InitDatabase {

    private Logger logger = LoggerFactory.getLogger(InitDatabase.class);

    @Resource
    private Environment environment;

    @Bean
    public DataSource getDataSource(){
        DataSource ds = new DriverManagerDataSource(environment.getRequiredProperty("url"),
                environment.getRequiredProperty("user"),
                environment.getRequiredProperty("password"));
        Connection conn = null;
        try {
            conn = ds.getConnection();

        } catch (SQLException e) {
            logger.error("数据源获取失败！！",e);
        }

//        try {
//            String[] tables = environment.getRequiredProperty("tables").split(",");
//            ResultSet resultSet = conn.getMetaData().getTables(conn.getCatalog(), null, null, new String[]{"TABLE"});
//            List<String> list = new ArrayList<String>();
//            while(resultSet.next()){
//                list.add(resultSet.getString("TABLE_NAME"));;
//            }
//
//            for(String t : tables){
//                if(!list.contains(t.toUpperCase())){
//                    conn.createStatement().execute(environment.getRequiredProperty(t));
//                }
//            }

//			conn.createStatement().execute("create table test (user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),username varchar(50) not null);");
//        } catch (SQLException e) {
//            logger.error("表已创建！！",e);
//        }

        return ds;
    }
}
