alter schema public rename to mcopy;
ALTER CATALOG PUBLIC RENAME TO mcopy;
--用户表
create table users (user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),username varchar(50) not null,loginname VARCHAR(20) not null,password VARCHAR(20) not null,createtime DATETIME,userlevel CHAR(1));
--菜单表
create table menu (menu_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(start WITH 100),menuname VARCHAR(255),menuname_en VARCHAR(255),menulevel CHAR(1),usetemp CHAR(1),content CLOB,url varchar(255),parent INTEGER,status CHAR(1),sort VARCHAR(3));

--TAB表
CREATE TABLE tabs (tab_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 100),title varchar(255),menu_id integer, content CLOB,sort varchar(3));

--新闻中心
CREATE TABLE news (new_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 100),title VARCHAR(255),content CLOB,readcount INTEGER DEFAULT 0,createdate DATE);
